_wandb:
    value:
        cli_version: 0.24.1
        e:
            rp4oj4ecuwmpt55xs9s001w8zgyjcei6:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 24
                disk:
                    /:
                        total: "2014573477888"
                        used: "1624988680192"
                email: pazit.shefet@gmail.com
                executable: /home/shmuel/projects/temp/ydata/dsipProject/venv/bin/python3
                git:
                    commit: 7618ced504852dacf6ae0805707e26ccd00ee6ae
                    remote: https://github.com/roychek15/dsipProject
                host: infocore-pc3
                memory:
                    total: "134754512896"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /home/shmuel/projects/temp/ydata/dsipProject/train.py
                python: CPython 3.12.3
                root: /home/shmuel/projects/temp/ydata/dsipProject
                startedAt: "2026-02-04T13:11:17.417119Z"
                writerId: rp4oj4ecuwmpt55xs9s001w8zgyjcei6
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
n_estimators:
    value: 400
